General:
  Region: "eu-central-1"

Component:
  CIDR: "10.0.0.0/16"
  Tags:
    Name: "Custom-VPC"
    beta: "value2"
    gamma: "value3"
    
  PrivateSubnets:
    Subnet1:
      Mask: 26
      AZ: euc1-az3
      TAGS:
        Name: Red
    Subnet2:
      Mask: 27
      AZ: euc1-az1
      TAGS:
        Name: Green
    Subnet3:
      Mask: 28
      AZ: euc1-az1
      TAGS:
        Name: Blue
    Subnet4:
      Mask: 25
      AZ: euc1-az2
      TAGS:
        Name: Brown
    Subnet5:
      Mask: 28
      AZ: euc1-az3
      TAGS:
        Name: Orange
    Subnet6:
      Mask: 26
      AZ: euc1-az1
      TAGS:
        Name: Purple
    Subnet7:
      Mask: 25
      AZ: euc1-az2
      TAGS:
        Name: Black
